version: '3.7'
services:
  redis:
    container_name: coupon-redis
    image: redis:7.4-bookworm
    ports:
      - 6379:6379
  redis-insight:
    container_name: coupon-redis-insight
    image: redis/redisinsight
    ports:
      - 5540:5540
  mysql:
    container_name: coupon-mysql
    image: ubuntu/mysql:edge
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --explicit_defaults_for_timestamp=1
    ports:
      - 3307:3306
    environment:
      - MYSQL_DATABASE=coupon
      - MYSQL_USER=viva
      - MYSQL_PASSWORD=1234
      - MYSQL_ROOT_PASSWORD=1234
      - TZ=UTC
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d